/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.linearsolver;

public class operations_research_linear_solverJNI {
  public final static native int MPSolver_CLP_LINEAR_PROGRAMMING_get();
  public final static native int MPSolver_GLOP_LINEAR_PROGRAMMING_get();
  public final static native int MPSolver_CBC_MIXED_INTEGER_PROGRAMMING_get();
  public final static native int MPSolver_BOP_INTEGER_PROGRAMMING_get();
  public final static native long new_MPSolver(String jarg1, int jarg2);
  public final static native void delete_MPSolver(long jarg1);
  public final static native boolean MPSolver_supportsProblemType(int jarg1);
  public final static native void MPSolver_clear(long jarg1, MPSolver jarg1_);
  public final static native int MPSolver_numVariables(long jarg1, MPSolver jarg1_);
  public final static native long MPSolver_lookupVariableOrNull(long jarg1, MPSolver jarg1_, String jarg2);
  public final static native long MPSolver_makeVar(long jarg1, MPSolver jarg1_, double jarg2, double jarg3, boolean jarg4, String jarg5);
  public final static native long MPSolver_makeNumVar(long jarg1, MPSolver jarg1_, double jarg2, double jarg3, String jarg4);
  public final static native long MPSolver_makeIntVar(long jarg1, MPSolver jarg1_, double jarg2, double jarg3, String jarg4);
  public final static native long MPSolver_makeBoolVar(long jarg1, MPSolver jarg1_, String jarg2);
  public final static native int MPSolver_numConstraints(long jarg1, MPSolver jarg1_);
  public final static native long MPSolver_lookupConstraintOrNull(long jarg1, MPSolver jarg1_, String jarg2);
  public final static native long MPSolver_makeConstraint__SWIG_0(long jarg1, MPSolver jarg1_, double jarg2, double jarg3);
  public final static native long MPSolver_makeConstraint__SWIG_1(long jarg1, MPSolver jarg1_);
  public final static native long MPSolver_makeConstraint__SWIG_2(long jarg1, MPSolver jarg1_, double jarg2, double jarg3, String jarg4);
  public final static native long MPSolver_makeConstraint__SWIG_3(long jarg1, MPSolver jarg1_, String jarg2);
  public final static native long MPSolver_objective(long jarg1, MPSolver jarg1_);
  public final static native int MPSolver_NOT_SOLVED_get();
  public final static native int MPSolver_solve__SWIG_0(long jarg1, MPSolver jarg1_);
  public final static native int MPSolver_solve__SWIG_1(long jarg1, MPSolver jarg1_, long jarg2, MPSolverParameters jarg2_);
  public final static native double[] MPSolver_computeConstraintActivities(long jarg1, MPSolver jarg1_);
  public final static native boolean MPSolver_verifySolution(long jarg1, MPSolver jarg1_, double jarg2, boolean jarg3);
  public final static native void MPSolver_reset(long jarg1, MPSolver jarg1_);
  public final static native boolean MPSolver_setSolverSpecificParametersAsString(long jarg1, MPSolver jarg1_, String jarg2);
  public final static native int MPSolver_FREE_get();
  public final static native double MPSolver_infinity();
  public final static native void MPSolver_enableOutput(long jarg1, MPSolver jarg1_);
  public final static native void MPSolver_suppressOutput(long jarg1, MPSolver jarg1_);
  public final static native void MPSolver_setTimeLimit(long jarg1, MPSolver jarg1_, long jarg2);
  public final static native long MPSolver_wallTime(long jarg1, MPSolver jarg1_);
  public final static native long MPSolver_iterations(long jarg1, MPSolver jarg1_);
  public final static native long MPSolver_nodes(long jarg1, MPSolver jarg1_);
  public final static native double MPSolver_computeExactConditionNumber(long jarg1, MPSolver jarg1_);
  public final static native String MPSolver_exportModelAsLpFormat(long jarg1, MPSolver jarg1_, boolean jarg2);
  public final static native String MPSolver_exportModelAsMpsFormat(long jarg1, MPSolver jarg1_, boolean jarg2, boolean jarg3);
  public final static native void MPObjective_clear(long jarg1, MPObjective jarg1_);
  public final static native void MPObjective_setCoefficient(long jarg1, MPObjective jarg1_, long jarg2, MPVariable jarg2_, double jarg3);
  public final static native double MPObjective_getCoefficient(long jarg1, MPObjective jarg1_, long jarg2, MPVariable jarg2_);
  public final static native void MPObjective_setOffset(long jarg1, MPObjective jarg1_, double jarg2);
  public final static native double MPObjective_offset(long jarg1, MPObjective jarg1_);
  public final static native void MPObjective_addOffset(long jarg1, MPObjective jarg1_, double jarg2);
  public final static native void MPObjective_setOptimizationDirection(long jarg1, MPObjective jarg1_, boolean jarg2);
  public final static native void MPObjective_setMinimization(long jarg1, MPObjective jarg1_);
  public final static native void MPObjective_setMaximization(long jarg1, MPObjective jarg1_);
  public final static native boolean MPObjective_maximization(long jarg1, MPObjective jarg1_);
  public final static native boolean MPObjective_minimization(long jarg1, MPObjective jarg1_);
  public final static native double MPObjective_value(long jarg1, MPObjective jarg1_);
  public final static native double MPObjective_bestBound(long jarg1, MPObjective jarg1_);
  public final static native void delete_MPObjective(long jarg1);
  public final static native String MPVariable_name(long jarg1, MPVariable jarg1_);
  public final static native void MPVariable_setInteger(long jarg1, MPVariable jarg1_, boolean jarg2);
  public final static native double MPVariable_solutionValue(long jarg1, MPVariable jarg1_);
  public final static native int MPVariable_index(long jarg1, MPVariable jarg1_);
  public final static native double MPVariable_lb(long jarg1, MPVariable jarg1_);
  public final static native double MPVariable_ub(long jarg1, MPVariable jarg1_);
  public final static native void MPVariable_setLb(long jarg1, MPVariable jarg1_, double jarg2);
  public final static native void MPVariable_setUb(long jarg1, MPVariable jarg1_, double jarg2);
  public final static native void MPVariable_setBounds(long jarg1, MPVariable jarg1_, double jarg2, double jarg3);
  public final static native double MPVariable_reducedCost(long jarg1, MPVariable jarg1_);
  public final static native int MPVariable_basisStatus(long jarg1, MPVariable jarg1_);
  public final static native void delete_MPVariable(long jarg1);
  public final static native String MPConstraint_name(long jarg1, MPConstraint jarg1_);
  public final static native void MPConstraint_setCoefficient(long jarg1, MPConstraint jarg1_, long jarg2, MPVariable jarg2_, double jarg3);
  public final static native double MPConstraint_getCoefficient(long jarg1, MPConstraint jarg1_, long jarg2, MPVariable jarg2_);
  public final static native double MPConstraint_lb(long jarg1, MPConstraint jarg1_);
  public final static native double MPConstraint_ub(long jarg1, MPConstraint jarg1_);
  public final static native void MPConstraint_setLb(long jarg1, MPConstraint jarg1_, double jarg2);
  public final static native void MPConstraint_setUb(long jarg1, MPConstraint jarg1_, double jarg2);
  public final static native void MPConstraint_setBounds(long jarg1, MPConstraint jarg1_, double jarg2, double jarg3);
  public final static native boolean MPConstraint_isLazy(long jarg1, MPConstraint jarg1_);
  public final static native void MPConstraint_setIsLazy(long jarg1, MPConstraint jarg1_, boolean jarg2);
  public final static native int MPConstraint_index(long jarg1, MPConstraint jarg1_);
  public final static native double MPConstraint_dualValue(long jarg1, MPConstraint jarg1_);
  public final static native int MPConstraint_basisStatus(long jarg1, MPConstraint jarg1_);
  public final static native void delete_MPConstraint(long jarg1);
  public final static native int MPSolverParameters_RELATIVE_MIP_GAP_get();
  public final static native double MPSolverParameters_kDefaultPrimalTolerance_get();
  public final static native long new_MPSolverParameters();
  public final static native void MPSolverParameters_setDoubleParam(long jarg1, MPSolverParameters jarg1_, int jarg2, double jarg3);
  public final static native double MPSolverParameters_getDoubleParam(long jarg1, MPSolverParameters jarg1_, int jarg2);
  public final static native void delete_MPSolverParameters(long jarg1);
}
