/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.graph;

public class MinCostFlowBase {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MinCostFlowBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MinCostFlowBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_graphJNI.delete_MinCostFlowBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MinCostFlowBase() {
    this(operations_research_graphJNI.new_MinCostFlowBase(), true);
  }

  public final static class Status {
    public final static MinCostFlowBase.Status NOT_SOLVED = new MinCostFlowBase.Status("NOT_SOLVED");
    public final static MinCostFlowBase.Status OPTIMAL = new MinCostFlowBase.Status("OPTIMAL");
    public final static MinCostFlowBase.Status FEASIBLE = new MinCostFlowBase.Status("FEASIBLE");
    public final static MinCostFlowBase.Status INFEASIBLE = new MinCostFlowBase.Status("INFEASIBLE");
    public final static MinCostFlowBase.Status UNBALANCED = new MinCostFlowBase.Status("UNBALANCED");
    public final static MinCostFlowBase.Status BAD_RESULT = new MinCostFlowBase.Status("BAD_RESULT");
    public final static MinCostFlowBase.Status BAD_COST_RANGE = new MinCostFlowBase.Status("BAD_COST_RANGE");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Status swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Status.class + " with value " + swigValue);
    }

    private Status(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Status(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Status(String swigName, Status swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Status[] swigValues = { NOT_SOLVED, OPTIMAL, FEASIBLE, INFEASIBLE, UNBALANCED, BAD_RESULT, BAD_COST_RANGE };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
