= Google OR-Tools for Java

image:https://travis-ci.org/oliviercailloux/google-or-tools-java.svg?branch=master["Build Status", link="https://travis-ci.org/oliviercailloux/google-or-tools-java"]
image:https://maven-badges.herokuapp.com/maven-central/io.github.oliviercailloux/google-or-tools/badge.svg["Artifact on Maven Central", link="http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22io.github.oliviercailloux%22%20a%3A%22google-or-tools%22"]

A project to publish Google OR-Tools as a dependable dependency in Maven.

This project contains no specific source code (except for a simple https://github.com/oliviercailloux/google-or-tools-java/blob/master/src/test/java/io/github/oliviercailloux/google_or_tools/TestRun.java[test] class). Everything comes from Google OR-Tools.

== Making Google OR-Tools for Java
Here is how to re-make this project from scratch (except for the test class and `pom.xml`, which I created manually).

* install https://developers.google.com/optimization/introduction/installing/source.html#prerequisites_linux[prerequisites]
* set dest variable (see below)
* clone https://github.com/google/or-tools[OR-Tools] in a folder whose full path contain no space
* `git checkout v6.7.2`
* `make third_party`
* `make java`
* `mv "ortools/gen/com" "${dest}/src/main/java/"`
* `rmdir "${dest}/src/main/java/com/google/ortools/flatzinc" "${dest}/src/main/java/com/google/ortools/properties" "${dest}/src/main/java/com/google/ortools/sat"`
* Download the library for https://developers.google.com/optimization/#or-tools-downloads-for-c-java-or-c[Ubuntu 14] (the version run by Travis)
* Extract the archive, move `or-tools_Ubuntu-14.04-64bit_v6.7.4981/lib/libortools.so` and `libjniortools.so` to `"${dest}/lib/"`

=== Lib (attempt)
Attempting to build the library (instead of downloading it) leads to Travis https://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx[failing] the Maven test. Here is what I tried (and abandoned).

* observe that the produced library binds to the absolute path it is built in (that’s no good): `readelf -a lib/libjniortools.so | grep PATH`
* let’s change that: `patchelf --set-rpath '$ORIGIN' lib/libjniortools.so`
* `mv lib/*.so "${dest}/lib/"`

== Refs
* https://github.com/google/or-tools/issues/202 
* https://github.com/scijava/native-lib-loader 

== Previous attempt
Here is a simpler way, but which I abandoned as it does not produce source code and as embedding the library is not clean.

* Downloaded or-tools_Debian-9.4-64bit_v6.7.4981.tar.gz from https://github.com/google/or-tools/releases
* (Noticed that or-tools_Debian-9.4-64bit_v6.7.4981/lib/libjniortools.so and or-tools_Ubuntu-17.10-64bit_v6.7.4981/lib/libjniortools.so differ)
* Extracted or-tools_Debian-9.4-64bit_v6.7.4981.tar.gz to or-tools_Debian-9.4-64bit_v6.7.4981/
* Extracted or-tools_Debian-9.4-64bit_v6.7.4981/lib/com.google.ortools.jar to src/main/resources
* mkdir -p src/main/resources/META-INF/lib/linux_64 ; mv or-tools_Debian-9.4-64bit_v6.7.4981/lib/libjniortools.so src/main/resources/META-INF/lib/linux_64
