/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.algorithms;

public class operations_research_algorithmsJNI {
  public final static native int KnapsackSolver_KNAPSACK_BRUTE_FORCE_SOLVER_get();
  public final static native int KnapsackSolver_KNAPSACK_64ITEMS_SOLVER_get();
  public final static native int KnapsackSolver_KNAPSACK_DYNAMIC_PROGRAMMING_SOLVER_get();
  public final static native int KnapsackSolver_KNAPSACK_MULTIDIMENSION_BRANCH_AND_BOUND_SOLVER_get();
  public final static native long new_KnapsackSolver__SWIG_0(String jarg1);
  public final static native long new_KnapsackSolver__SWIG_1(int jarg1, String jarg2);
  public final static native void delete_KnapsackSolver(long jarg1);
  public final static native void KnapsackSolver_init(long jarg1, KnapsackSolver jarg1_, long[] jarg2, long[][] jarg3, long[] jarg4);
  public final static native long KnapsackSolver_solve(long jarg1, KnapsackSolver jarg1_);
  public final static native boolean KnapsackSolver_bestSolutionContains(long jarg1, KnapsackSolver jarg1_, int jarg2);
}
