/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class Assignment extends PropagationBaseObject {
  private transient long swigCPtr;

  protected Assignment(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.Assignment_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Assignment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_Assignment(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Assignment(Solver s) {
    this(operations_research_constraint_solverJNI.new_Assignment__SWIG_0(Solver.getCPtr(s), s), true);
  }

  public Assignment(Assignment copy) {
    this(operations_research_constraint_solverJNI.new_Assignment__SWIG_1(Assignment.getCPtr(copy), copy), true);
  }

  public void clear() {
    operations_research_constraint_solverJNI.Assignment_clear(swigCPtr, this);
  }

  public boolean empty() {
    return operations_research_constraint_solverJNI.Assignment_empty(swigCPtr, this);
  }

  public int size() {
    return operations_research_constraint_solverJNI.Assignment_size(swigCPtr, this);
  }

  public int NumIntVars() {
    return operations_research_constraint_solverJNI.Assignment_NumIntVars(swigCPtr, this);
  }

  public int NumIntervalVars() {
    return operations_research_constraint_solverJNI.Assignment_NumIntervalVars(swigCPtr, this);
  }

  public int NumSequenceVars() {
    return operations_research_constraint_solverJNI.Assignment_NumSequenceVars(swigCPtr, this);
  }

  public void store() {
    operations_research_constraint_solverJNI.Assignment_store(swigCPtr, this);
  }

  public void restore() {
    operations_research_constraint_solverJNI.Assignment_restore(swigCPtr, this);
  }

  public boolean load(String filename) {
    return operations_research_constraint_solverJNI.Assignment_load__SWIG_0(swigCPtr, this, filename);
  }

  public void load(SWIGTYPE_p_operations_research__AssignmentProto assignment_proto) {
    operations_research_constraint_solverJNI.Assignment_load__SWIG_1(swigCPtr, this, SWIGTYPE_p_operations_research__AssignmentProto.getCPtr(assignment_proto));
  }

  public boolean save(String filename) {
    return operations_research_constraint_solverJNI.Assignment_save__SWIG_0(swigCPtr, this, filename);
  }

  public void save(SWIGTYPE_p_operations_research__AssignmentProto assignment_proto) {
    operations_research_constraint_solverJNI.Assignment_save__SWIG_1(swigCPtr, this, SWIGTYPE_p_operations_research__AssignmentProto.getCPtr(assignment_proto));
  }

  public void addObjective(IntVar v) {
    operations_research_constraint_solverJNI.Assignment_addObjective(swigCPtr, this, IntVar.getCPtr(v), v);
  }

  public IntVar objective() {
    long cPtr = operations_research_constraint_solverJNI.Assignment_objective(swigCPtr, this);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public boolean hasObjective() {
    return operations_research_constraint_solverJNI.Assignment_hasObjective(swigCPtr, this);
  }

  public long objectiveMin() {
    return operations_research_constraint_solverJNI.Assignment_objectiveMin(swigCPtr, this);
  }

  public long objectiveMax() {
    return operations_research_constraint_solverJNI.Assignment_objectiveMax(swigCPtr, this);
  }

  public long objectiveValue() {
    return operations_research_constraint_solverJNI.Assignment_objectiveValue(swigCPtr, this);
  }

  public boolean objectiveBound() {
    return operations_research_constraint_solverJNI.Assignment_objectiveBound(swigCPtr, this);
  }

  public void setObjectiveMin(long m) {
    operations_research_constraint_solverJNI.Assignment_setObjectiveMin(swigCPtr, this, m);
  }

  public void setObjectiveMax(long m) {
    operations_research_constraint_solverJNI.Assignment_setObjectiveMax(swigCPtr, this, m);
  }

  public void setObjectiveValue(long value) {
    operations_research_constraint_solverJNI.Assignment_setObjectiveValue(swigCPtr, this, value);
  }

  public void setObjectiveRange(long l, long u) {
    operations_research_constraint_solverJNI.Assignment_setObjectiveRange(swigCPtr, this, l, u);
  }

  public IntVarElement add(IntVar var) {
    long cPtr = operations_research_constraint_solverJNI.Assignment_add__SWIG_0(swigCPtr, this, IntVar.getCPtr(var), var);
    return (cPtr == 0) ? null : new IntVarElement(cPtr, false);
  }

  public void add(IntVar[] vars) {
    operations_research_constraint_solverJNI.Assignment_add__SWIG_1(swigCPtr, this, vars);
  }

  public IntVarElement FastAdd(IntVar var) {
    long cPtr = operations_research_constraint_solverJNI.Assignment_FastAdd__SWIG_0(swigCPtr, this, IntVar.getCPtr(var), var);
    return (cPtr == 0) ? null : new IntVarElement(cPtr, false);
  }

  public long min(IntVar var) {
    return operations_research_constraint_solverJNI.Assignment_min(swigCPtr, this, IntVar.getCPtr(var), var);
  }

  public long max(IntVar var) {
    return operations_research_constraint_solverJNI.Assignment_max(swigCPtr, this, IntVar.getCPtr(var), var);
  }

  public long value(IntVar var) {
    return operations_research_constraint_solverJNI.Assignment_value(swigCPtr, this, IntVar.getCPtr(var), var);
  }

  public boolean bound(IntVar var) {
    return operations_research_constraint_solverJNI.Assignment_bound(swigCPtr, this, IntVar.getCPtr(var), var);
  }

  public void setMin(IntVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setMin(swigCPtr, this, IntVar.getCPtr(var), var, m);
  }

  public void setMax(IntVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setMax(swigCPtr, this, IntVar.getCPtr(var), var, m);
  }

  public void setRange(IntVar var, long l, long u) {
    operations_research_constraint_solverJNI.Assignment_setRange(swigCPtr, this, IntVar.getCPtr(var), var, l, u);
  }

  public void setValue(IntVar var, long value) {
    operations_research_constraint_solverJNI.Assignment_setValue(swigCPtr, this, IntVar.getCPtr(var), var, value);
  }

  public IntervalVarElement add(IntervalVar var) {
    long cPtr = operations_research_constraint_solverJNI.Assignment_add__SWIG_2(swigCPtr, this, IntervalVar.getCPtr(var), var);
    return (cPtr == 0) ? null : new IntervalVarElement(cPtr, false);
  }

  public void add(IntervalVar[] vars) {
    operations_research_constraint_solverJNI.Assignment_add__SWIG_3(swigCPtr, this, vars);
  }

  public IntervalVarElement FastAdd(IntervalVar var) {
    long cPtr = operations_research_constraint_solverJNI.Assignment_FastAdd__SWIG_1(swigCPtr, this, IntervalVar.getCPtr(var), var);
    return (cPtr == 0) ? null : new IntervalVarElement(cPtr, false);
  }

  public long startMin(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_startMin(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long startMax(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_startMax(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long startValue(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_startValue(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long durationMin(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_durationMin(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long durationMax(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_durationMax(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long durationValue(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_durationValue(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long endMin(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_endMin(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long endMax(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_endMax(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long endValue(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_endValue(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long performedMin(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_performedMin(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long performedMax(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_performedMax(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public long performedValue(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_performedValue(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public void setStartMin(IntervalVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setStartMin(swigCPtr, this, IntervalVar.getCPtr(var), var, m);
  }

  public void setStartMax(IntervalVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setStartMax(swigCPtr, this, IntervalVar.getCPtr(var), var, m);
  }

  public void setStartRange(IntervalVar var, long mi, long ma) {
    operations_research_constraint_solverJNI.Assignment_setStartRange(swigCPtr, this, IntervalVar.getCPtr(var), var, mi, ma);
  }

  public void setStartValue(IntervalVar var, long value) {
    operations_research_constraint_solverJNI.Assignment_setStartValue(swigCPtr, this, IntervalVar.getCPtr(var), var, value);
  }

  public void setDurationMin(IntervalVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setDurationMin(swigCPtr, this, IntervalVar.getCPtr(var), var, m);
  }

  public void setDurationMax(IntervalVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setDurationMax(swigCPtr, this, IntervalVar.getCPtr(var), var, m);
  }

  public void setDurationRange(IntervalVar var, long mi, long ma) {
    operations_research_constraint_solverJNI.Assignment_setDurationRange(swigCPtr, this, IntervalVar.getCPtr(var), var, mi, ma);
  }

  public void setDurationValue(IntervalVar var, long value) {
    operations_research_constraint_solverJNI.Assignment_setDurationValue(swigCPtr, this, IntervalVar.getCPtr(var), var, value);
  }

  public void setEndMin(IntervalVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setEndMin(swigCPtr, this, IntervalVar.getCPtr(var), var, m);
  }

  public void setEndMax(IntervalVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setEndMax(swigCPtr, this, IntervalVar.getCPtr(var), var, m);
  }

  public void setEndRange(IntervalVar var, long mi, long ma) {
    operations_research_constraint_solverJNI.Assignment_setEndRange(swigCPtr, this, IntervalVar.getCPtr(var), var, mi, ma);
  }

  public void setEndValue(IntervalVar var, long value) {
    operations_research_constraint_solverJNI.Assignment_setEndValue(swigCPtr, this, IntervalVar.getCPtr(var), var, value);
  }

  public void setPerformedMin(IntervalVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setPerformedMin(swigCPtr, this, IntervalVar.getCPtr(var), var, m);
  }

  public void setPerformedMax(IntervalVar var, long m) {
    operations_research_constraint_solverJNI.Assignment_setPerformedMax(swigCPtr, this, IntervalVar.getCPtr(var), var, m);
  }

  public void setPerformedRange(IntervalVar var, long mi, long ma) {
    operations_research_constraint_solverJNI.Assignment_setPerformedRange(swigCPtr, this, IntervalVar.getCPtr(var), var, mi, ma);
  }

  public void setPerformedValue(IntervalVar var, long value) {
    operations_research_constraint_solverJNI.Assignment_setPerformedValue(swigCPtr, this, IntervalVar.getCPtr(var), var, value);
  }

  public SequenceVarElement add(SequenceVar var) {
    long cPtr = operations_research_constraint_solverJNI.Assignment_add__SWIG_4(swigCPtr, this, SequenceVar.getCPtr(var), var);
    return (cPtr == 0) ? null : new SequenceVarElement(cPtr, false);
  }

  public void add(SequenceVar[] vars) {
    operations_research_constraint_solverJNI.Assignment_add__SWIG_5(swigCPtr, this, vars);
  }

  public SequenceVarElement FastAdd(SequenceVar var) {
    long cPtr = operations_research_constraint_solverJNI.Assignment_FastAdd__SWIG_2(swigCPtr, this, SequenceVar.getCPtr(var), var);
    return (cPtr == 0) ? null : new SequenceVarElement(cPtr, false);
  }

  public int[] ForwardSequence(SequenceVar var) {
  return operations_research_constraint_solverJNI.Assignment_ForwardSequence(swigCPtr, this, SequenceVar.getCPtr(var), var);
}

  public int[] BackwardSequence(SequenceVar var) {
  return operations_research_constraint_solverJNI.Assignment_BackwardSequence(swigCPtr, this, SequenceVar.getCPtr(var), var);
}

  public int[] Unperformed(SequenceVar var) {
  return operations_research_constraint_solverJNI.Assignment_Unperformed(swigCPtr, this, SequenceVar.getCPtr(var), var);
}

  public void SetSequence(SequenceVar var, int[] forward_sequence, int[] backward_sequence, int[] unperformed) {
    operations_research_constraint_solverJNI.Assignment_SetSequence(swigCPtr, this, SequenceVar.getCPtr(var), var, forward_sequence, backward_sequence, unperformed);
  }

  public void SetForwardSequence(SequenceVar var, int[] forward_sequence) {
    operations_research_constraint_solverJNI.Assignment_SetForwardSequence(swigCPtr, this, SequenceVar.getCPtr(var), var, forward_sequence);
  }

  public void SetBackwardSequence(SequenceVar var, int[] backward_sequence) {
    operations_research_constraint_solverJNI.Assignment_SetBackwardSequence(swigCPtr, this, SequenceVar.getCPtr(var), var, backward_sequence);
  }

  public void SetUnperformed(SequenceVar var, int[] unperformed) {
    operations_research_constraint_solverJNI.Assignment_SetUnperformed(swigCPtr, this, SequenceVar.getCPtr(var), var, unperformed);
  }

  public void activate(IntVar var) {
    operations_research_constraint_solverJNI.Assignment_activate__SWIG_0(swigCPtr, this, IntVar.getCPtr(var), var);
  }

  public void deactivate(IntVar var) {
    operations_research_constraint_solverJNI.Assignment_deactivate__SWIG_0(swigCPtr, this, IntVar.getCPtr(var), var);
  }

  public boolean activated(IntVar var) {
    return operations_research_constraint_solverJNI.Assignment_activated__SWIG_0(swigCPtr, this, IntVar.getCPtr(var), var);
  }

  public void activate(IntervalVar var) {
    operations_research_constraint_solverJNI.Assignment_activate__SWIG_1(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public void deactivate(IntervalVar var) {
    operations_research_constraint_solverJNI.Assignment_deactivate__SWIG_1(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public boolean activated(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_activated__SWIG_1(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public void activate(SequenceVar var) {
    operations_research_constraint_solverJNI.Assignment_activate__SWIG_2(swigCPtr, this, SequenceVar.getCPtr(var), var);
  }

  public void deactivate(SequenceVar var) {
    operations_research_constraint_solverJNI.Assignment_deactivate__SWIG_2(swigCPtr, this, SequenceVar.getCPtr(var), var);
  }

  public boolean activated(SequenceVar var) {
    return operations_research_constraint_solverJNI.Assignment_activated__SWIG_2(swigCPtr, this, SequenceVar.getCPtr(var), var);
  }

  public void activateObjective() {
    operations_research_constraint_solverJNI.Assignment_activateObjective(swigCPtr, this);
  }

  public void deactivateObjective() {
    operations_research_constraint_solverJNI.Assignment_deactivateObjective(swigCPtr, this);
  }

  public boolean activatedObjective() {
    return operations_research_constraint_solverJNI.Assignment_activatedObjective(swigCPtr, this);
  }

  public String toString() {
    return operations_research_constraint_solverJNI.Assignment_toString(swigCPtr, this);
  }

  public boolean contains(IntVar var) {
    return operations_research_constraint_solverJNI.Assignment_contains__SWIG_0(swigCPtr, this, IntVar.getCPtr(var), var);
  }

  public boolean contains(IntervalVar var) {
    return operations_research_constraint_solverJNI.Assignment_contains__SWIG_1(swigCPtr, this, IntervalVar.getCPtr(var), var);
  }

  public boolean contains(SequenceVar var) {
    return operations_research_constraint_solverJNI.Assignment_contains__SWIG_2(swigCPtr, this, SequenceVar.getCPtr(var), var);
  }

  public void CopyIntersection(Assignment assignment) {
    operations_research_constraint_solverJNI.Assignment_CopyIntersection(swigCPtr, this, Assignment.getCPtr(assignment), assignment);
  }

  public void copy(Assignment assignment) {
    operations_research_constraint_solverJNI.Assignment_copy(swigCPtr, this, Assignment.getCPtr(assignment), assignment);
  }

  public AssignmentIntContainer intVarContainer() {
    return new AssignmentIntContainer(operations_research_constraint_solverJNI.Assignment_intVarContainer(swigCPtr, this), false);
  }

  public AssignmentIntContainer MutableIntVarContainer() {
    long cPtr = operations_research_constraint_solverJNI.Assignment_MutableIntVarContainer(swigCPtr, this);
    return (cPtr == 0) ? null : new AssignmentIntContainer(cPtr, false);
  }

  public SWIGTYPE_p_operations_research__AssignmentContainerT_operations_research__IntervalVar_operations_research__IntervalVarElement_t IntervalVarContainer() {
    return new SWIGTYPE_p_operations_research__AssignmentContainerT_operations_research__IntervalVar_operations_research__IntervalVarElement_t(operations_research_constraint_solverJNI.Assignment_IntervalVarContainer(swigCPtr, this), false);
  }

  public SWIGTYPE_p_operations_research__AssignmentContainerT_operations_research__IntervalVar_operations_research__IntervalVarElement_t MutableIntervalVarContainer() {
    long cPtr = operations_research_constraint_solverJNI.Assignment_MutableIntervalVarContainer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_operations_research__AssignmentContainerT_operations_research__IntervalVar_operations_research__IntervalVarElement_t(cPtr, false);
  }

  public SWIGTYPE_p_operations_research__AssignmentContainerT_operations_research__SequenceVar_operations_research__SequenceVarElement_t SequenceVarContainer() {
    return new SWIGTYPE_p_operations_research__AssignmentContainerT_operations_research__SequenceVar_operations_research__SequenceVarElement_t(operations_research_constraint_solverJNI.Assignment_SequenceVarContainer(swigCPtr, this), false);
  }

  public SWIGTYPE_p_operations_research__AssignmentContainerT_operations_research__SequenceVar_operations_research__SequenceVarElement_t MutableSequenceVarContainer() {
    long cPtr = operations_research_constraint_solverJNI.Assignment_MutableSequenceVarContainer(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_operations_research__AssignmentContainerT_operations_research__SequenceVar_operations_research__SequenceVarElement_t(cPtr, false);
  }

}
