/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class BaseObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BaseObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BaseObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_BaseObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BaseObject() {
    this(operations_research_constraint_solverJNI.new_BaseObject(), true);
  }

  public String toString() {
    return operations_research_constraint_solverJNI.BaseObject_toString(swigCPtr, this);
  }

}
