// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/solver_parameters.proto

package com.google.ortools.constraintsolver;

public interface ConstraintSolverParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.ConstraintSolverParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * This parameter indicates if the solver should compress the trail
   * during the search. No compression means that the solver will be faster,
   * but will use more memory.
   * </pre>
   *
   * <code>.operations_research.ConstraintSolverParameters.TrailCompression compress_trail = 1;</code>
   */
  int getCompressTrailValue();
  /**
   * <pre>
   * This parameter indicates if the solver should compress the trail
   * during the search. No compression means that the solver will be faster,
   * but will use more memory.
   * </pre>
   *
   * <code>.operations_research.ConstraintSolverParameters.TrailCompression compress_trail = 1;</code>
   */
  com.google.ortools.constraintsolver.ConstraintSolverParameters.TrailCompression getCompressTrail();

  /**
   * <pre>
   * This parameter indicates the default size of a block of the trail.
   * Compression applies at the block level.
   * </pre>
   *
   * <code>int32 trail_block_size = 2;</code>
   */
  int getTrailBlockSize();

  /**
   * <pre>
   * When a sum/min/max operation is applied on a large array, this
   * array is recursively split into blocks of size 'array_split_size'.
   * </pre>
   *
   * <code>int32 array_split_size = 3;</code>
   */
  int getArraySplitSize();

  /**
   * <pre>
   * This parameters indicates if the solver should store the names of
   * the objets it manages.
   * </pre>
   *
   * <code>bool store_names = 4;</code>
   */
  boolean getStoreNames();

  /**
   * <pre>
   * Create names for cast variables.
   * </pre>
   *
   * <code>bool name_cast_variables = 5;</code>
   */
  boolean getNameCastVariables();

  /**
   * <pre>
   * Should anonymous variables be given a name.
   * </pre>
   *
   * <code>bool name_all_variables = 6;</code>
   */
  boolean getNameAllVariables();

  /**
   * <pre>
   * Activate propagation profiling.
   * </pre>
   *
   * <code>bool profile_propagation = 7;</code>
   */
  boolean getProfilePropagation();

  /**
   * <pre>
   * Export propagation profiling data to file.
   * </pre>
   *
   * <code>string profile_file = 8;</code>
   */
  java.lang.String getProfileFile();
  /**
   * <pre>
   * Export propagation profiling data to file.
   * </pre>
   *
   * <code>string profile_file = 8;</code>
   */
  com.google.protobuf.ByteString
      getProfileFileBytes();

  /**
   * <pre>
   * Activate local search profiling.
   * </pre>
   *
   * <code>bool profile_local_search = 16;</code>
   */
  boolean getProfileLocalSearch();

  /**
   * <pre>
   * Print local search profiling data after solving.
   * </pre>
   *
   * <code>bool print_local_search_profile = 17;</code>
   */
  boolean getPrintLocalSearchProfile();

  /**
   * <pre>
   * Activate propagate tracing.
   * </pre>
   *
   * <code>bool trace_propagation = 9;</code>
   */
  boolean getTracePropagation();

  /**
   * <pre>
   * Trace search.
   * </pre>
   *
   * <code>bool trace_search = 10;</code>
   */
  boolean getTraceSearch();

  /**
   * <pre>
   * Print the model before solving.
   * </pre>
   *
   * <code>bool print_model = 11;</code>
   */
  boolean getPrintModel();

  /**
   * <pre>
   * Print model statistics before solving.
   * </pre>
   *
   * <code>bool print_model_stats = 12;</code>
   */
  boolean getPrintModelStats();

  /**
   * <pre>
   * Print added constraints.
   * </pre>
   *
   * <code>bool print_added_constraints = 13;</code>
   */
  boolean getPrintAddedConstraints();

  /**
   * <pre>
   * Export model to file.
   * </pre>
   *
   * <code>string export_file = 14;</code>
   */
  java.lang.String getExportFile();
  /**
   * <pre>
   * Export model to file.
   * </pre>
   *
   * <code>string export_file = 14;</code>
   */
  com.google.protobuf.ByteString
      getExportFileBytes();

  /**
   * <code>bool disable_solve = 15;</code>
   */
  boolean getDisableSolve();

  /**
   * <pre>
   * Control the implementation of the table constraint.
   * </pre>
   *
   * <code>bool use_compact_table = 100;</code>
   */
  boolean getUseCompactTable();

  /**
   * <code>bool use_small_table = 101;</code>
   */
  boolean getUseSmallTable();

  /**
   * <code>bool use_sat_table = 102;</code>
   */
  boolean getUseSatTable();

  /**
   * <code>int32 ac4r_table_threshold = 103;</code>
   */
  int getAc4RTableThreshold();

  /**
   * <code>bool use_mdd_table = 104;</code>
   */
  boolean getUseMddTable();

  /**
   * <pre>
   * Control the propagation of the cumulative constraint.
   * </pre>
   *
   * <code>bool use_cumulative_edge_finder = 105;</code>
   */
  boolean getUseCumulativeEdgeFinder();

  /**
   * <code>bool use_cumulative_time_table = 106;</code>
   */
  boolean getUseCumulativeTimeTable();

  /**
   * <code>bool use_cumulative_time_table_sync = 112;</code>
   */
  boolean getUseCumulativeTimeTableSync();

  /**
   * <code>bool use_sequence_high_demand_tasks = 107;</code>
   */
  boolean getUseSequenceHighDemandTasks();

  /**
   * <code>bool use_all_possible_disjunctions = 108;</code>
   */
  boolean getUseAllPossibleDisjunctions();

  /**
   * <code>int32 max_edge_finder_size = 109;</code>
   */
  int getMaxEdgeFinderSize();

  /**
   * <pre>
   * Control the propagation of the diffn constraint.
   * </pre>
   *
   * <code>bool diffn_use_cumulative = 110;</code>
   */
  boolean getDiffnUseCumulative();

  /**
   * <pre>
   * Control the implementation of the element constraint.
   * </pre>
   *
   * <code>bool use_element_rmq = 111;</code>
   */
  boolean getUseElementRmq();
}
