/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class Constraint extends PropagationBaseObject {
  private transient long swigCPtr;

  protected Constraint(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.Constraint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Constraint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_Constraint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void Post() {
    operations_research_constraint_solverJNI.Constraint_Post(swigCPtr, this);
  }

  public void InitialPropagate() {
    operations_research_constraint_solverJNI.Constraint_InitialPropagate(swigCPtr, this);
  }

  public String toString() {
    return operations_research_constraint_solverJNI.Constraint_toString(swigCPtr, this);
  }

  public void PostAndPropagate() {
    operations_research_constraint_solverJNI.Constraint_PostAndPropagate(swigCPtr, this);
  }

  public void accept(ModelVisitor visitor) {
    operations_research_constraint_solverJNI.Constraint_accept(swigCPtr, this, ModelVisitor.getCPtr(visitor), visitor);
  }

  public boolean IsCastConstraint() {
    return operations_research_constraint_solverJNI.Constraint_IsCastConstraint(swigCPtr, this);
  }

  public IntVar var() {
    long cPtr = operations_research_constraint_solverJNI.Constraint_var(swigCPtr, this);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

}
