/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class IntervalVar extends PropagationBaseObject {
  private transient long swigCPtr;

  protected IntervalVar(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.IntervalVar_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntervalVar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_IntervalVar(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static long getKMinValidValue() {
    return operations_research_constraint_solverJNI.IntervalVar_kMinValidValue_get();
  }

  public static long getKMaxValidValue() {
    return operations_research_constraint_solverJNI.IntervalVar_kMaxValidValue_get();
  }

  public long StartMin() {
    return operations_research_constraint_solverJNI.IntervalVar_StartMin(swigCPtr, this);
  }

  public long StartMax() {
    return operations_research_constraint_solverJNI.IntervalVar_StartMax(swigCPtr, this);
  }

  public void SetStartMin(long m) {
    operations_research_constraint_solverJNI.IntervalVar_SetStartMin(swigCPtr, this, m);
  }

  public void SetStartMax(long m) {
    operations_research_constraint_solverJNI.IntervalVar_SetStartMax(swigCPtr, this, m);
  }

  public void SetStartRange(long mi, long ma) {
    operations_research_constraint_solverJNI.IntervalVar_SetStartRange(swigCPtr, this, mi, ma);
  }

  public long OldStartMin() {
    return operations_research_constraint_solverJNI.IntervalVar_OldStartMin(swigCPtr, this);
  }

  public long OldStartMax() {
    return operations_research_constraint_solverJNI.IntervalVar_OldStartMax(swigCPtr, this);
  }

  public void WhenStartRange(Demon d) {
    operations_research_constraint_solverJNI.IntervalVar_WhenStartRange__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenStartRange(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntervalVar_WhenStartRange__SWIG_1(swigCPtr, this, closure);
  }

  public void WhenStartBound(Demon d) {
    operations_research_constraint_solverJNI.IntervalVar_WhenStartBound__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenStartBound(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntervalVar_WhenStartBound__SWIG_1(swigCPtr, this, closure);
  }

  public long DurationMin() {
    return operations_research_constraint_solverJNI.IntervalVar_DurationMin(swigCPtr, this);
  }

  public long DurationMax() {
    return operations_research_constraint_solverJNI.IntervalVar_DurationMax(swigCPtr, this);
  }

  public void SetDurationMin(long m) {
    operations_research_constraint_solverJNI.IntervalVar_SetDurationMin(swigCPtr, this, m);
  }

  public void SetDurationMax(long m) {
    operations_research_constraint_solverJNI.IntervalVar_SetDurationMax(swigCPtr, this, m);
  }

  public void SetDurationRange(long mi, long ma) {
    operations_research_constraint_solverJNI.IntervalVar_SetDurationRange(swigCPtr, this, mi, ma);
  }

  public long OldDurationMin() {
    return operations_research_constraint_solverJNI.IntervalVar_OldDurationMin(swigCPtr, this);
  }

  public long OldDurationMax() {
    return operations_research_constraint_solverJNI.IntervalVar_OldDurationMax(swigCPtr, this);
  }

  public void WhenDurationRange(Demon d) {
    operations_research_constraint_solverJNI.IntervalVar_WhenDurationRange__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenDurationRange(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntervalVar_WhenDurationRange__SWIG_1(swigCPtr, this, closure);
  }

  public void WhenDurationBound(Demon d) {
    operations_research_constraint_solverJNI.IntervalVar_WhenDurationBound__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenDurationBound(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntervalVar_WhenDurationBound__SWIG_1(swigCPtr, this, closure);
  }

  public long EndMin() {
    return operations_research_constraint_solverJNI.IntervalVar_EndMin(swigCPtr, this);
  }

  public long EndMax() {
    return operations_research_constraint_solverJNI.IntervalVar_EndMax(swigCPtr, this);
  }

  public void SetEndMin(long m) {
    operations_research_constraint_solverJNI.IntervalVar_SetEndMin(swigCPtr, this, m);
  }

  public void SetEndMax(long m) {
    operations_research_constraint_solverJNI.IntervalVar_SetEndMax(swigCPtr, this, m);
  }

  public void SetEndRange(long mi, long ma) {
    operations_research_constraint_solverJNI.IntervalVar_SetEndRange(swigCPtr, this, mi, ma);
  }

  public long OldEndMin() {
    return operations_research_constraint_solverJNI.IntervalVar_OldEndMin(swigCPtr, this);
  }

  public long OldEndMax() {
    return operations_research_constraint_solverJNI.IntervalVar_OldEndMax(swigCPtr, this);
  }

  public void WhenEndRange(Demon d) {
    operations_research_constraint_solverJNI.IntervalVar_WhenEndRange__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenEndRange(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntervalVar_WhenEndRange__SWIG_1(swigCPtr, this, closure);
  }

  public void WhenEndBound(Demon d) {
    operations_research_constraint_solverJNI.IntervalVar_WhenEndBound__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenEndBound(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntervalVar_WhenEndBound__SWIG_1(swigCPtr, this, closure);
  }

  public boolean MustBePerformed() {
    return operations_research_constraint_solverJNI.IntervalVar_MustBePerformed(swigCPtr, this);
  }

  public boolean MayBePerformed() {
    return operations_research_constraint_solverJNI.IntervalVar_MayBePerformed(swigCPtr, this);
  }

  public boolean CannotBePerformed() {
    return operations_research_constraint_solverJNI.IntervalVar_CannotBePerformed(swigCPtr, this);
  }

  public boolean IsPerformedBound() {
    return operations_research_constraint_solverJNI.IntervalVar_IsPerformedBound(swigCPtr, this);
  }

  public void SetPerformed(boolean val) {
    operations_research_constraint_solverJNI.IntervalVar_SetPerformed(swigCPtr, this, val);
  }

  public boolean WasPerformedBound() {
    return operations_research_constraint_solverJNI.IntervalVar_WasPerformedBound(swigCPtr, this);
  }

  public void WhenPerformedBound(Demon d) {
    operations_research_constraint_solverJNI.IntervalVar_WhenPerformedBound__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenPerformedBound(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntervalVar_WhenPerformedBound__SWIG_1(swigCPtr, this, closure);
  }

  public void WhenAnything(Demon d) {
    operations_research_constraint_solverJNI.IntervalVar_WhenAnything__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenAnything(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntervalVar_WhenAnything__SWIG_1(swigCPtr, this, closure);
  }

  public IntExpr StartExpr() {
    long cPtr = operations_research_constraint_solverJNI.IntervalVar_StartExpr(swigCPtr, this);
    return (cPtr == 0) ? null : new IntExpr(cPtr, false);
  }

  public IntExpr DurationExpr() {
    long cPtr = operations_research_constraint_solverJNI.IntervalVar_DurationExpr(swigCPtr, this);
    return (cPtr == 0) ? null : new IntExpr(cPtr, false);
  }

  public IntExpr EndExpr() {
    long cPtr = operations_research_constraint_solverJNI.IntervalVar_EndExpr(swigCPtr, this);
    return (cPtr == 0) ? null : new IntExpr(cPtr, false);
  }

  public IntExpr PerformedExpr() {
    long cPtr = operations_research_constraint_solverJNI.IntervalVar_PerformedExpr(swigCPtr, this);
    return (cPtr == 0) ? null : new IntExpr(cPtr, false);
  }

  public IntExpr SafeStartExpr(long unperformed_value) {
    long cPtr = operations_research_constraint_solverJNI.IntervalVar_SafeStartExpr(swigCPtr, this, unperformed_value);
    return (cPtr == 0) ? null : new IntExpr(cPtr, false);
  }

  public IntExpr SafeDurationExpr(long unperformed_value) {
    long cPtr = operations_research_constraint_solverJNI.IntervalVar_SafeDurationExpr(swigCPtr, this, unperformed_value);
    return (cPtr == 0) ? null : new IntExpr(cPtr, false);
  }

  public IntExpr SafeEndExpr(long unperformed_value) {
    long cPtr = operations_research_constraint_solverJNI.IntervalVar_SafeEndExpr(swigCPtr, this, unperformed_value);
    return (cPtr == 0) ? null : new IntExpr(cPtr, false);
  }

  public void accept(ModelVisitor visitor) {
    operations_research_constraint_solverJNI.IntervalVar_accept(swigCPtr, this, ModelVisitor.getCPtr(visitor), visitor);
  }

}
