/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class IntIntToLong {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IntIntToLong(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntIntToLong obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_IntIntToLong(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.IntIntToLong_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.IntIntToLong_change_ownership(this, swigCPtr, true);
  }

  public long run(int arg0, int arg1) {
    return operations_research_constraint_solverJNI.IntIntToLong_run(swigCPtr, this, arg0, arg1);
  }

  public IntIntToLong() {
    this(operations_research_constraint_solverJNI.new_IntIntToLong(), true);
    operations_research_constraint_solverJNI.IntIntToLong_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
