/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class IntVar extends IntExpr {
  private transient long swigCPtr;

  protected IntVar(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.IntVar_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_IntVar(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean isVar() {
    return operations_research_constraint_solverJNI.IntVar_isVar(swigCPtr, this);
  }

  public IntVar var() {
    long cPtr = operations_research_constraint_solverJNI.IntVar_var(swigCPtr, this);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public long value() {
    return operations_research_constraint_solverJNI.IntVar_value(swigCPtr, this);
  }

  public void removeValue(long v) {
    operations_research_constraint_solverJNI.IntVar_removeValue(swigCPtr, this, v);
  }

  public void removeInterval(long l, long u) {
    operations_research_constraint_solverJNI.IntVar_removeInterval(swigCPtr, this, l, u);
  }

  public void removeValues(long[] values) {
    operations_research_constraint_solverJNI.IntVar_removeValues(swigCPtr, this, values);
  }

  public void setValue(long[] values) {
    operations_research_constraint_solverJNI.IntVar_setValue(swigCPtr, this, values);
  }

  public void WhenBound(Demon d) {
    operations_research_constraint_solverJNI.IntVar_WhenBound__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenBound(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntVar_WhenBound__SWIG_1(swigCPtr, this, closure);
  }

  public void WhenDomain(Demon d) {
    operations_research_constraint_solverJNI.IntVar_WhenDomain__SWIG_0(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void WhenDomain(VoidToVoid closure) {
    operations_research_constraint_solverJNI.IntVar_WhenDomain__SWIG_1(swigCPtr, this, closure);
  }

  public java.math.BigInteger Size() {
    return operations_research_constraint_solverJNI.IntVar_Size(swigCPtr, this);
  }

  public boolean contains(long v) {
    return operations_research_constraint_solverJNI.IntVar_contains(swigCPtr, this, v);
  }

  public IntVarIterator MakeHoleIterator(boolean reversible) {
    long cPtr = operations_research_constraint_solverJNI.IntVar_MakeHoleIterator(swigCPtr, this, reversible);
    return (cPtr == 0) ? null : new IntVarIterator(cPtr, false);
  }

  public IntVarIterator MakeDomainIterator(boolean reversible) {
    long cPtr = operations_research_constraint_solverJNI.IntVar_MakeDomainIterator(swigCPtr, this, reversible);
    return (cPtr == 0) ? null : new IntVarIterator(cPtr, false);
  }

  public long OldMin() {
    return operations_research_constraint_solverJNI.IntVar_OldMin(swigCPtr, this);
  }

  public long OldMax() {
    return operations_research_constraint_solverJNI.IntVar_OldMax(swigCPtr, this);
  }

  public int VarType() {
    return operations_research_constraint_solverJNI.IntVar_VarType(swigCPtr, this);
  }

  public void accept(ModelVisitor visitor) {
    operations_research_constraint_solverJNI.IntVar_accept(swigCPtr, this, ModelVisitor.getCPtr(visitor), visitor);
  }

  public IntVar IsEqual(long constant) {
    long cPtr = operations_research_constraint_solverJNI.IntVar_IsEqual(swigCPtr, this, constant);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public IntVar IsDifferent(long constant) {
    long cPtr = operations_research_constraint_solverJNI.IntVar_IsDifferent(swigCPtr, this, constant);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public IntVar IsGreaterOrEqual(long constant) {
    long cPtr = operations_research_constraint_solverJNI.IntVar_IsGreaterOrEqual(swigCPtr, this, constant);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public IntVar IsLessOrEqual(long constant) {
    long cPtr = operations_research_constraint_solverJNI.IntVar_IsLessOrEqual(swigCPtr, this, constant);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public int index() {
    return operations_research_constraint_solverJNI.IntVar_index(swigCPtr, this);
  }

}
