/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class IntVarLocalSearchOperator extends IntVarLocalSearchOperatorTemplate {
  private transient long swigCPtr;

  protected IntVarLocalSearchOperator(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.IntVarLocalSearchOperator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVarLocalSearchOperator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_IntVarLocalSearchOperator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.IntVarLocalSearchOperator_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.IntVarLocalSearchOperator_change_ownership(this, swigCPtr, true);
  }

  public IntVarLocalSearchOperator() {
    this(operations_research_constraint_solverJNI.new_IntVarLocalSearchOperator__SWIG_0(), true);
    operations_research_constraint_solverJNI.IntVarLocalSearchOperator_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public IntVarLocalSearchOperator(IntVar[] vars) {
    this(operations_research_constraint_solverJNI.new_IntVarLocalSearchOperator__SWIG_1(vars), true);
    operations_research_constraint_solverJNI.IntVarLocalSearchOperator_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  protected boolean oneNeighbor() {
    return (getClass() == IntVarLocalSearchOperator.class) ? operations_research_constraint_solverJNI.IntVarLocalSearchOperator_oneNeighbor(swigCPtr, this) : operations_research_constraint_solverJNI.IntVarLocalSearchOperator_oneNeighborSwigExplicitIntVarLocalSearchOperator(swigCPtr, this);
  }

}
