/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class IntVarLocalSearchFilter extends LocalSearchFilter {
  private transient long swigCPtr;

  protected IntVarLocalSearchFilter(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.IntVarLocalSearchFilter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVarLocalSearchFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_IntVarLocalSearchFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.IntVarLocalSearchFilter_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.IntVarLocalSearchFilter_change_ownership(this, swigCPtr, true);
  }

  public IntVarLocalSearchFilter(IntVar[] vars, LongToVoid objective_callback) {
    this(operations_research_constraint_solverJNI.new_IntVarLocalSearchFilter__SWIG_0(vars, objective_callback), true);
    operations_research_constraint_solverJNI.IntVarLocalSearchFilter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public IntVarLocalSearchFilter(IntVar[] vars) {
    this(operations_research_constraint_solverJNI.new_IntVarLocalSearchFilter__SWIG_1(vars), true);
    operations_research_constraint_solverJNI.IntVarLocalSearchFilter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void synchronize(Assignment assignment, Assignment delta) {
    operations_research_constraint_solverJNI.IntVarLocalSearchFilter_synchronize(swigCPtr, this, Assignment.getCPtr(assignment), assignment, Assignment.getCPtr(delta), delta);
  }

  public void InjectObjectiveValue(long objective_value) {
    if (getClass() == IntVarLocalSearchFilter.class) operations_research_constraint_solverJNI.IntVarLocalSearchFilter_InjectObjectiveValue(swigCPtr, this, objective_value); else operations_research_constraint_solverJNI.IntVarLocalSearchFilter_InjectObjectiveValueSwigExplicitIntVarLocalSearchFilter(swigCPtr, this, objective_value);
  }

  public void addVars(IntVar[] vars) {
    operations_research_constraint_solverJNI.IntVarLocalSearchFilter_addVars(swigCPtr, this, vars);
  }

  public int size() {
    return operations_research_constraint_solverJNI.IntVarLocalSearchFilter_size(swigCPtr, this);
  }

  public IntVar var(int index) {
    long cPtr = operations_research_constraint_solverJNI.IntVarLocalSearchFilter_var(swigCPtr, this, index);
    return (cPtr == 0) ? null : new IntVar(cPtr, false);
  }

  public long value(int index) {
    return operations_research_constraint_solverJNI.IntVarLocalSearchFilter_value(swigCPtr, this, index);
  }

  public boolean IsVarSynced(int index) {
    return operations_research_constraint_solverJNI.IntVarLocalSearchFilter_IsVarSynced(swigCPtr, this, index);
  }

  protected void onSynchronize(Assignment delta) {
    if (getClass() == IntVarLocalSearchFilter.class) operations_research_constraint_solverJNI.IntVarLocalSearchFilter_onSynchronize(swigCPtr, this, Assignment.getCPtr(delta), delta); else operations_research_constraint_solverJNI.IntVarLocalSearchFilter_onSynchronizeSwigExplicitIntVarLocalSearchFilter(swigCPtr, this, Assignment.getCPtr(delta), delta);
  }

  public int index(IntVar var) {
    return operations_research_constraint_solverJNI.IntVarLocalSearchFilter_index(swigCPtr, this, IntVar.getCPtr(var), var);
  }

}
