/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class IntVarFilteredDecisionBuilder extends DecisionBuilder {
  private transient long swigCPtr;

  protected IntVarFilteredDecisionBuilder(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.IntVarFilteredDecisionBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntVarFilteredDecisionBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_IntVarFilteredDecisionBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Decision nextWrap(Solver solver) {
    long cPtr = operations_research_constraint_solverJNI.IntVarFilteredDecisionBuilder_nextWrap(swigCPtr, this, Solver.getCPtr(solver), solver);
    return (cPtr == 0) ? null : new Decision(cPtr, false);
  }

  public boolean BuildSolution() {
    return operations_research_constraint_solverJNI.IntVarFilteredDecisionBuilder_BuildSolution(swigCPtr, this);
  }

  public long number_of_decisions() {
    return operations_research_constraint_solverJNI.IntVarFilteredDecisionBuilder_number_of_decisions(swigCPtr, this);
  }

  public long number_of_rejects() {
    return operations_research_constraint_solverJNI.IntVarFilteredDecisionBuilder_number_of_rejects(swigCPtr, this);
  }

}
