/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class LocalSearchFilter extends BaseObject {
  private transient long swigCPtr;

  protected LocalSearchFilter(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.LocalSearchFilter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LocalSearchFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_LocalSearchFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean accept(Assignment delta, Assignment deltadelta) {
    return operations_research_constraint_solverJNI.LocalSearchFilter_accept(swigCPtr, this, Assignment.getCPtr(delta), delta, Assignment.getCPtr(deltadelta), deltadelta);
  }

  public void synchronize(Assignment assignment, Assignment delta) {
    operations_research_constraint_solverJNI.LocalSearchFilter_synchronize(swigCPtr, this, Assignment.getCPtr(assignment), assignment, Assignment.getCPtr(delta), delta);
  }

  public boolean isIncremental() {
    return operations_research_constraint_solverJNI.LocalSearchFilter_isIncremental(swigCPtr, this);
  }

}
