// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/routing_enums.proto

package com.google.ortools.constraintsolver;

public interface LocalSearchMetaheuristicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.LocalSearchMetaheuristic)
    com.google.protobuf.MessageOrBuilder {
}
