/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class LocalSearchMonitor extends SearchMonitor {
  private transient long swigCPtr;

  protected LocalSearchMonitor(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.LocalSearchMonitor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LocalSearchMonitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_LocalSearchMonitor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void BeginOperatorStart() {
    operations_research_constraint_solverJNI.LocalSearchMonitor_BeginOperatorStart(swigCPtr, this);
  }

  public void EndOperatorStart() {
    operations_research_constraint_solverJNI.LocalSearchMonitor_EndOperatorStart(swigCPtr, this);
  }

  public void BeginMakeNextNeighbor(LocalSearchOperator op) {
    operations_research_constraint_solverJNI.LocalSearchMonitor_BeginMakeNextNeighbor(swigCPtr, this, LocalSearchOperator.getCPtr(op), op);
  }

  public void EndMakeNextNeighbor(LocalSearchOperator op, boolean neighbor_found, Assignment delta, Assignment deltadelta) {
    operations_research_constraint_solverJNI.LocalSearchMonitor_EndMakeNextNeighbor(swigCPtr, this, LocalSearchOperator.getCPtr(op), op, neighbor_found, Assignment.getCPtr(delta), delta, Assignment.getCPtr(deltadelta), deltadelta);
  }

  public void BeginFilterNeighbor(LocalSearchOperator op) {
    operations_research_constraint_solverJNI.LocalSearchMonitor_BeginFilterNeighbor(swigCPtr, this, LocalSearchOperator.getCPtr(op), op);
  }

  public void EndFilterNeighbor(LocalSearchOperator op, boolean neighbor_found) {
    operations_research_constraint_solverJNI.LocalSearchMonitor_EndFilterNeighbor(swigCPtr, this, LocalSearchOperator.getCPtr(op), op, neighbor_found);
  }

  public void BeginAcceptNeighbor(LocalSearchOperator op) {
    operations_research_constraint_solverJNI.LocalSearchMonitor_BeginAcceptNeighbor(swigCPtr, this, LocalSearchOperator.getCPtr(op), op);
  }

  public void EndAcceptNeighbor(LocalSearchOperator op, boolean neighbor_found) {
    operations_research_constraint_solverJNI.LocalSearchMonitor_EndAcceptNeighbor(swigCPtr, this, LocalSearchOperator.getCPtr(op), op, neighbor_found);
  }

  public void BeginFiltering(LocalSearchFilter filter) {
    operations_research_constraint_solverJNI.LocalSearchMonitor_BeginFiltering(swigCPtr, this, LocalSearchFilter.getCPtr(filter), filter);
  }

  public void EndFiltering(LocalSearchFilter filter, boolean reject) {
    operations_research_constraint_solverJNI.LocalSearchMonitor_EndFiltering(swigCPtr, this, LocalSearchFilter.getCPtr(filter), filter, reject);
  }

  public void Install() {
    operations_research_constraint_solverJNI.LocalSearchMonitor_Install(swigCPtr, this);
  }

}
