/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class LongToVoid {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LongToVoid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LongToVoid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_LongToVoid(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.LongToVoid_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.LongToVoid_change_ownership(this, swigCPtr, true);
  }

  public void run(long i) {
    operations_research_constraint_solverJNI.LongToVoid_run(swigCPtr, this, i);
  }

  public LongToVoid() {
    this(operations_research_constraint_solverJNI.new_LongToVoid(), true);
    operations_research_constraint_solverJNI.LongToVoid_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
