/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class LongLongLongToBoolean {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LongLongLongToBoolean(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LongLongLongToBoolean obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_LongLongLongToBoolean(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.LongLongLongToBoolean_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.LongLongLongToBoolean_change_ownership(this, swigCPtr, true);
  }

  public boolean run(long i, long j, long k) {
    return operations_research_constraint_solverJNI.LongLongLongToBoolean_run(swigCPtr, this, i, j, k);
  }

  public LongLongLongToBoolean() {
    this(operations_research_constraint_solverJNI.new_LongLongLongToBoolean(), true);
    operations_research_constraint_solverJNI.LongLongLongToBoolean_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
