/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class NodeEvaluator2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NodeEvaluator2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NodeEvaluator2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_NodeEvaluator2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.NodeEvaluator2_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.NodeEvaluator2_change_ownership(this, swigCPtr, true);
  }

  public NodeEvaluator2() {
    this(operations_research_constraint_solverJNI.new_NodeEvaluator2(), true);
    operations_research_constraint_solverJNI.NodeEvaluator2_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public long run(int i, int j) {
    return operations_research_constraint_solverJNI.NodeEvaluator2_run(swigCPtr, this, i, j);
  }

  public SWIGTYPE_p_ResultCallback2T_long_long_RoutingNodeIndex_RoutingNodeIndex_t getPermanentCallback() {
    long cPtr = operations_research_constraint_solverJNI.NodeEvaluator2_getPermanentCallback(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ResultCallback2T_long_long_RoutingNodeIndex_RoutingNodeIndex_t(cPtr, false);
  }

}
