/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class NoGoodManager extends SearchMonitor {
  private transient long swigCPtr;

  protected NoGoodManager(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.NoGoodManager_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NoGoodManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_NoGoodManager(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void Clear() {
    operations_research_constraint_solverJNI.NoGoodManager_Clear(swigCPtr, this);
  }

  public NoGood MakeNoGood() {
    long cPtr = operations_research_constraint_solverJNI.NoGoodManager_MakeNoGood(swigCPtr, this);
    return (cPtr == 0) ? null : new NoGood(cPtr, false);
  }

  public void AddNoGood(NoGood nogood) {
    operations_research_constraint_solverJNI.NoGoodManager_AddNoGood(swigCPtr, this, NoGood.getCPtr(nogood), nogood);
  }

  public int NoGoodCount() {
    return operations_research_constraint_solverJNI.NoGoodManager_NoGoodCount(swigCPtr, this);
  }

  public String toString() {
    return operations_research_constraint_solverJNI.NoGoodManager_toString(swigCPtr, this);
  }

  public void enterSearch() {
    operations_research_constraint_solverJNI.NoGoodManager_enterSearch(swigCPtr, this);
  }

  public void beginNextDecision(DecisionBuilder db) {
    operations_research_constraint_solverJNI.NoGoodManager_beginNextDecision(swigCPtr, this, DecisionBuilder.getCPtr(db), db);
  }

  public boolean acceptSolution() {
    return operations_research_constraint_solverJNI.NoGoodManager_acceptSolution(swigCPtr, this);
  }

}
