/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public interface operations_research_constraint_solverConstants {
  // VarTypes 
  public final static int UNSPECIFIED = operations_research_constraint_solverJNI.UNSPECIFIED_get();
  public final static int DOMAIN_INT_VAR = operations_research_constraint_solverJNI.DOMAIN_INT_VAR_get();
  public final static int BOOLEAN_VAR = operations_research_constraint_solverJNI.BOOLEAN_VAR_get();
  public final static int CONST_VAR = operations_research_constraint_solverJNI.CONST_VAR_get();
  public final static int VAR_ADD_CST = operations_research_constraint_solverJNI.VAR_ADD_CST_get();
  public final static int VAR_TIMES_CST = operations_research_constraint_solverJNI.VAR_TIMES_CST_get();
  public final static int CST_SUB_VAR = operations_research_constraint_solverJNI.CST_SUB_VAR_get();
  public final static int OPP_VAR = operations_research_constraint_solverJNI.OPP_VAR_get();
  public final static int TRACE_VAR = operations_research_constraint_solverJNI.TRACE_VAR_get();

}
