/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class PropagationBaseObject extends BaseObject {
  private transient long swigCPtr;

  protected PropagationBaseObject(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.PropagationBaseObject_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PropagationBaseObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_PropagationBaseObject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PropagationBaseObject(Solver s) {
    this(operations_research_constraint_solverJNI.new_PropagationBaseObject(Solver.getCPtr(s), s), true);
  }

  public String toString() {
    return operations_research_constraint_solverJNI.PropagationBaseObject_toString(swigCPtr, this);
  }

  public Solver solver() {
    long cPtr = operations_research_constraint_solverJNI.PropagationBaseObject_solver(swigCPtr, this);
    return (cPtr == 0) ? null : new Solver(cPtr, false);
  }

  public void FreezeQueue() {
    operations_research_constraint_solverJNI.PropagationBaseObject_FreezeQueue(swigCPtr, this);
  }

  public void UnfreezeQueue() {
    operations_research_constraint_solverJNI.PropagationBaseObject_UnfreezeQueue(swigCPtr, this);
  }

  public void EnqueueDelayedDemon(Demon d) {
    operations_research_constraint_solverJNI.PropagationBaseObject_EnqueueDelayedDemon(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void EnqueueVar(Demon d) {
    operations_research_constraint_solverJNI.PropagationBaseObject_EnqueueVar(swigCPtr, this, Demon.getCPtr(d), d);
  }

  public void ExecuteAll(SWIGTYPE_p_operations_research__SimpleRevFIFOT_operations_research__Demon_p_t demons) {
    operations_research_constraint_solverJNI.PropagationBaseObject_ExecuteAll(swigCPtr, this, SWIGTYPE_p_operations_research__SimpleRevFIFOT_operations_research__Demon_p_t.getCPtr(demons));
  }

  public void EnqueueAll(SWIGTYPE_p_operations_research__SimpleRevFIFOT_operations_research__Demon_p_t demons) {
    operations_research_constraint_solverJNI.PropagationBaseObject_EnqueueAll(swigCPtr, this, SWIGTYPE_p_operations_research__SimpleRevFIFOT_operations_research__Demon_p_t.getCPtr(demons));
  }

  public void reset_action_on_fail() {
    operations_research_constraint_solverJNI.PropagationBaseObject_reset_action_on_fail(swigCPtr, this);
  }

  public void set_variable_to_clean_on_fail(IntVar v) {
    operations_research_constraint_solverJNI.PropagationBaseObject_set_variable_to_clean_on_fail(swigCPtr, this, IntVar.getCPtr(v), v);
  }

  public String name() {
    return operations_research_constraint_solverJNI.PropagationBaseObject_name(swigCPtr, this);
  }

  public void setName(String name) {
    operations_research_constraint_solverJNI.PropagationBaseObject_setName(swigCPtr, this, name);
  }

  public boolean HasName() {
    return operations_research_constraint_solverJNI.PropagationBaseObject_HasName(swigCPtr, this);
  }

  public String BaseName() {
    return operations_research_constraint_solverJNI.PropagationBaseObject_BaseName(swigCPtr, this);
  }

}
