/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class RevPartialSequence {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RevPartialSequence(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RevPartialSequence obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_RevPartialSequence(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RevPartialSequence(int[] items) {
    this(operations_research_constraint_solverJNI.new_RevPartialSequence__SWIG_0(items), true);
  }

  public RevPartialSequence(int size) {
    this(operations_research_constraint_solverJNI.new_RevPartialSequence__SWIG_1(size), true);
  }

  public int NumFirstRanked() {
    return operations_research_constraint_solverJNI.RevPartialSequence_NumFirstRanked(swigCPtr, this);
  }

  public int NumLastRanked() {
    return operations_research_constraint_solverJNI.RevPartialSequence_NumLastRanked(swigCPtr, this);
  }

  public int Size() {
    return operations_research_constraint_solverJNI.RevPartialSequence_Size(swigCPtr, this);
  }

  public void RankFirst(Solver solver, int elt) {
    operations_research_constraint_solverJNI.RevPartialSequence_RankFirst(swigCPtr, this, Solver.getCPtr(solver), solver, elt);
  }

  public void RankLast(Solver solver, int elt) {
    operations_research_constraint_solverJNI.RevPartialSequence_RankLast(swigCPtr, this, Solver.getCPtr(solver), solver, elt);
  }

  public boolean IsRanked(int elt) {
    return operations_research_constraint_solverJNI.RevPartialSequence_IsRanked(swigCPtr, this, elt);
  }

  public String toString() {
    return operations_research_constraint_solverJNI.RevPartialSequence_toString(swigCPtr, this);
  }

}
