// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/routing_parameters.proto

package com.google.ortools.constraintsolver;

public interface RoutingModelParametersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:operations_research.RoutingModelParameters)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Parameters to use in the underlying constraint solver.
   * </pre>
   *
   * <code>.operations_research.ConstraintSolverParameters solver_parameters = 1;</code>
   */
  boolean hasSolverParameters();
  /**
   * <pre>
   * Parameters to use in the underlying constraint solver.
   * </pre>
   *
   * <code>.operations_research.ConstraintSolverParameters solver_parameters = 1;</code>
   */
  com.google.ortools.constraintsolver.ConstraintSolverParameters getSolverParameters();
  /**
   * <pre>
   * Parameters to use in the underlying constraint solver.
   * </pre>
   *
   * <code>.operations_research.ConstraintSolverParameters solver_parameters = 1;</code>
   */
  com.google.ortools.constraintsolver.ConstraintSolverParametersOrBuilder getSolverParametersOrBuilder();

  /**
   * <pre>
   * Advanced settings.
   * If set to true reduction of the underlying constraint model will be
   * attempted when all vehicles have exactly the same cost structure. This can
   * result in significant speedups.
   * </pre>
   *
   * <code>bool reduce_vehicle_cost_model = 2;</code>
   */
  boolean getReduceVehicleCostModel();

  /**
   * <pre>
   * Cache callback calls if the number of nodes in the model is less or equal
   * to this value.
   * </pre>
   *
   * <code>int32 max_callback_cache_size = 3;</code>
   */
  int getMaxCallbackCacheSize();
}
