/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class RoutingFilteredDecisionBuilder extends IntVarFilteredDecisionBuilder {
  private transient long swigCPtr;

  protected RoutingFilteredDecisionBuilder(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.RoutingFilteredDecisionBuilder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RoutingFilteredDecisionBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_RoutingFilteredDecisionBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RoutingModel model() {
    long cPtr = operations_research_constraint_solverJNI.RoutingFilteredDecisionBuilder_model(swigCPtr, this);
    return (cPtr == 0) ? null : new RoutingModel(cPtr, false);
  }

  public boolean InitializeRoutes() {
    return operations_research_constraint_solverJNI.RoutingFilteredDecisionBuilder_InitializeRoutes(swigCPtr, this);
  }

  public int GetStartChainEnd(int vehicle) {
    return operations_research_constraint_solverJNI.RoutingFilteredDecisionBuilder_GetStartChainEnd(swigCPtr, this, vehicle);
  }

  public void MakeDisjunctionNodesUnperformed(long node) {
    operations_research_constraint_solverJNI.RoutingFilteredDecisionBuilder_MakeDisjunctionNodesUnperformed(swigCPtr, this, node);
  }

  public void MakeUnassignedNodesUnperformed() {
    operations_research_constraint_solverJNI.RoutingFilteredDecisionBuilder_MakeUnassignedNodesUnperformed(swigCPtr, this);
  }

}
