// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/routing_parameters.proto

package com.google.ortools.constraintsolver;

public final class RoutingParameters {
  private RoutingParameters() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingSearchParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_operations_research_RoutingSearchParameters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_operations_research_RoutingModelParameters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_operations_research_RoutingModelParameters_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2ortools/constraint_solver/routing_para" +
      "meters.proto\022\023operations_research\032-ortoo" +
      "ls/constraint_solver/routing_enums.proto" +
      "\0321ortools/constraint_solver/solver_param" +
      "eters.proto\"\203\n\n\027RoutingSearchParameters\022" +
      "Q\n\027first_solution_strategy\030\001 \001(\01620.opera" +
      "tions_research.FirstSolutionStrategy.Val" +
      "ue\022,\n$use_filtered_first_solution_strate" +
      "gy\030\002 \001(\010\022\037\n\027savings_neighbors_ratio\030\016 \001(" +
      "\001\022 \n\030savings_add_reverse_arcs\030\017 \001(\010\022m\n\026l" +
      "ocal_search_operators\030\003 \001(\0132M.operations" +
      "_research.RoutingSearchParameters.LocalS" +
      "earchNeighborhoodOperators\022W\n\032local_sear" +
      "ch_metaheuristic\030\004 \001(\01623.operations_rese" +
      "arch.LocalSearchMetaheuristic.Value\022.\n&g" +
      "uided_local_search_lambda_coefficient\030\005 " +
      "\001(\001\022\036\n\026use_depth_first_search\030\006 \001(\010\022\031\n\021o" +
      "ptimization_step\030\007 \001(\003\022\026\n\016solution_limit" +
      "\030\010 \001(\003\022\025\n\rtime_limit_ms\030\t \001(\003\022\031\n\021lns_tim" +
      "e_limit_ms\030\n \001(\003\022\035\n\025use_light_propagatio" +
      "n\030\013 \001(\010\022\'\n\037fingerprint_arc_cost_evaluato" +
      "rs\030\014 \001(\010\022\022\n\nlog_search\030\r \001(\010\032\312\004\n LocalSe" +
      "archNeighborhoodOperators\022\024\n\014use_relocat" +
      "e\030\001 \001(\010\022\031\n\021use_relocate_pair\030\002 \001(\010\022\036\n\026us" +
      "e_relocate_neighbors\030\003 \001(\010\022\024\n\014use_exchan" +
      "ge\030\004 \001(\010\022\021\n\tuse_cross\030\005 \001(\010\022\032\n\022use_cross" +
      "_exchange\030\006 \001(\010\022\023\n\013use_two_opt\030\007 \001(\010\022\022\n\n" +
      "use_or_opt\030\010 \001(\010\022\031\n\021use_lin_kernighan\030\t " +
      "\001(\010\022\023\n\013use_tsp_opt\030\n \001(\010\022\027\n\017use_make_act" +
      "ive\030\013 \001(\010\022$\n\034use_relocate_and_make_activ" +
      "e\030\025 \001(\010\022\031\n\021use_make_inactive\030\014 \001(\010\022\037\n\027us" +
      "e_make_chain_inactive\030\r \001(\010\022\027\n\017use_swap_" +
      "active\030\016 \001(\010\022 \n\030use_extended_swap_active" +
      "\030\017 \001(\010\022!\n\031use_node_pair_swap_active\030\024 \001(" +
      "\010\022\024\n\014use_path_lns\030\020 \001(\010\022\031\n\021use_full_path" +
      "_lns\030\021 \001(\010\022\023\n\013use_tsp_lns\030\022 \001(\010\022\030\n\020use_i" +
      "nactive_lns\030\023 \001(\010\"\250\001\n\026RoutingModelParame" +
      "ters\022J\n\021solver_parameters\030\001 \001(\0132/.operat" +
      "ions_research.ConstraintSolverParameters" +
      "\022!\n\031reduce_vehicle_cost_model\030\002 \001(\010\022\037\n\027m" +
      "ax_callback_cache_size\030\003 \001(\005BI\n#com.goog" +
      "le.ortools.constraintsolverP\001\252\002\037Google.O" +
      "rTools.ConstraintSolverb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.ortools.constraintsolver.RoutingEnums.getDescriptor(),
          com.google.ortools.constraintsolver.SolverParameters.getDescriptor(),
        }, assigner);
    internal_static_operations_research_RoutingSearchParameters_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_operations_research_RoutingSearchParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_operations_research_RoutingSearchParameters_descriptor,
        new java.lang.String[] { "FirstSolutionStrategy", "UseFilteredFirstSolutionStrategy", "SavingsNeighborsRatio", "SavingsAddReverseArcs", "LocalSearchOperators", "LocalSearchMetaheuristic", "GuidedLocalSearchLambdaCoefficient", "UseDepthFirstSearch", "OptimizationStep", "SolutionLimit", "TimeLimitMs", "LnsTimeLimitMs", "UseLightPropagation", "FingerprintArcCostEvaluators", "LogSearch", });
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor =
      internal_static_operations_research_RoutingSearchParameters_descriptor.getNestedTypes().get(0);
    internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_operations_research_RoutingSearchParameters_LocalSearchNeighborhoodOperators_descriptor,
        new java.lang.String[] { "UseRelocate", "UseRelocatePair", "UseRelocateNeighbors", "UseExchange", "UseCross", "UseCrossExchange", "UseTwoOpt", "UseOrOpt", "UseLinKernighan", "UseTspOpt", "UseMakeActive", "UseRelocateAndMakeActive", "UseMakeInactive", "UseMakeChainInactive", "UseSwapActive", "UseExtendedSwapActive", "UseNodePairSwapActive", "UsePathLns", "UseFullPathLns", "UseTspLns", "UseInactiveLns", });
    internal_static_operations_research_RoutingModelParameters_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_operations_research_RoutingModelParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_operations_research_RoutingModelParameters_descriptor,
        new java.lang.String[] { "SolverParameters", "ReduceVehicleCostModel", "MaxCallbackCacheSize", });
    com.google.ortools.constraintsolver.RoutingEnums.getDescriptor();
    com.google.ortools.constraintsolver.SolverParameters.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
