/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class SearchMonitor extends BaseObject {
  private transient long swigCPtr;

  protected SearchMonitor(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.SearchMonitor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SearchMonitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_SearchMonitor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.SearchMonitor_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.SearchMonitor_change_ownership(this, swigCPtr, true);
  }

  public SearchMonitor(Solver s) {
    this(operations_research_constraint_solverJNI.new_SearchMonitor(Solver.getCPtr(s), s), true);
    operations_research_constraint_solverJNI.SearchMonitor_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void enterSearch() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_enterSearch(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_enterSearchSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public void restartSearch() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_restartSearch(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_restartSearchSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public void ExitSearch() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_ExitSearch(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_ExitSearchSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public void beginNextDecision(DecisionBuilder b) {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_beginNextDecision(swigCPtr, this, DecisionBuilder.getCPtr(b), b); else operations_research_constraint_solverJNI.SearchMonitor_beginNextDecisionSwigExplicitSearchMonitor(swigCPtr, this, DecisionBuilder.getCPtr(b), b);
  }

  public void endNextDecision(DecisionBuilder b, Decision d) {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_endNextDecision(swigCPtr, this, DecisionBuilder.getCPtr(b), b, Decision.getCPtr(d), d); else operations_research_constraint_solverJNI.SearchMonitor_endNextDecisionSwigExplicitSearchMonitor(swigCPtr, this, DecisionBuilder.getCPtr(b), b, Decision.getCPtr(d), d);
  }

  public void applyDecision(Decision d) {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_applyDecision(swigCPtr, this, Decision.getCPtr(d), d); else operations_research_constraint_solverJNI.SearchMonitor_applyDecisionSwigExplicitSearchMonitor(swigCPtr, this, Decision.getCPtr(d), d);
  }

  public void refuteDecision(Decision d) {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_refuteDecision(swigCPtr, this, Decision.getCPtr(d), d); else operations_research_constraint_solverJNI.SearchMonitor_refuteDecisionSwigExplicitSearchMonitor(swigCPtr, this, Decision.getCPtr(d), d);
  }

  public void afterDecision(Decision d, boolean apply) {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_afterDecision(swigCPtr, this, Decision.getCPtr(d), d, apply); else operations_research_constraint_solverJNI.SearchMonitor_afterDecisionSwigExplicitSearchMonitor(swigCPtr, this, Decision.getCPtr(d), d, apply);
  }

  public void beginFail() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_beginFail(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_beginFailSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public void endFail() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_endFail(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_endFailSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public void beginInitialPropagation() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_beginInitialPropagation(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_beginInitialPropagationSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public void endInitialPropagation() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_endInitialPropagation(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_endInitialPropagationSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public boolean acceptSolution() {
    return (getClass() == SearchMonitor.class) ? operations_research_constraint_solverJNI.SearchMonitor_acceptSolution(swigCPtr, this) : operations_research_constraint_solverJNI.SearchMonitor_acceptSolutionSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public boolean atSolution() {
    return (getClass() == SearchMonitor.class) ? operations_research_constraint_solverJNI.SearchMonitor_atSolution(swigCPtr, this) : operations_research_constraint_solverJNI.SearchMonitor_atSolutionSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public void noMoreSolutions() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_noMoreSolutions(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_noMoreSolutionsSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public boolean localOptimum() {
    return (getClass() == SearchMonitor.class) ? operations_research_constraint_solverJNI.SearchMonitor_localOptimum(swigCPtr, this) : operations_research_constraint_solverJNI.SearchMonitor_localOptimumSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public boolean acceptDelta(Assignment delta, Assignment deltadelta) {
    return (getClass() == SearchMonitor.class) ? operations_research_constraint_solverJNI.SearchMonitor_acceptDelta(swigCPtr, this, Assignment.getCPtr(delta), delta, Assignment.getCPtr(deltadelta), deltadelta) : operations_research_constraint_solverJNI.SearchMonitor_acceptDeltaSwigExplicitSearchMonitor(swigCPtr, this, Assignment.getCPtr(delta), delta, Assignment.getCPtr(deltadelta), deltadelta);
  }

  public void acceptNeighbor() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_acceptNeighbor(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_acceptNeighborSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public Solver solver() {
    long cPtr = operations_research_constraint_solverJNI.SearchMonitor_solver(swigCPtr, this);
    return (cPtr == 0) ? null : new Solver(cPtr, false);
  }

  public void periodicCheck() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_periodicCheck(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_periodicCheckSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public int ProgressPercent() {
    return (getClass() == SearchMonitor.class) ? operations_research_constraint_solverJNI.SearchMonitor_ProgressPercent(swigCPtr, this) : operations_research_constraint_solverJNI.SearchMonitor_ProgressPercentSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public void accept(ModelVisitor visitor) {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_accept(swigCPtr, this, ModelVisitor.getCPtr(visitor), visitor); else operations_research_constraint_solverJNI.SearchMonitor_acceptSwigExplicitSearchMonitor(swigCPtr, this, ModelVisitor.getCPtr(visitor), visitor);
  }

  public void Install() {
    if (getClass() == SearchMonitor.class) operations_research_constraint_solverJNI.SearchMonitor_Install(swigCPtr, this); else operations_research_constraint_solverJNI.SearchMonitor_InstallSwigExplicitSearchMonitor(swigCPtr, this);
  }

  public final static int kNoProgress = operations_research_constraint_solverJNI.SearchMonitor_kNoProgress_get();
}
