/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class SequenceVarLocalSearchOperator extends SequenceVarLocalSearchOperatorTemplate {
  private transient long swigCPtr;

  protected SequenceVarLocalSearchOperator(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SequenceVarLocalSearchOperator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_SequenceVarLocalSearchOperator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_change_ownership(this, swigCPtr, true);
  }

  public SequenceVarLocalSearchOperator() {
    this(operations_research_constraint_solverJNI.new_SequenceVarLocalSearchOperator__SWIG_0(), true);
    operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public SequenceVarLocalSearchOperator(SequenceVar[] vars) {
    this(operations_research_constraint_solverJNI.new_SequenceVarLocalSearchOperator__SWIG_1(vars), true);
    operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public int[] Sequence(long index) {
  return operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_Sequence(swigCPtr, this, index);
}

  public int[] OldSequence(long index) {
  return operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_OldSequence(swigCPtr, this, index);
}

  public void SetForwardSequence(long index, int[] value) {
    operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_SetForwardSequence(swigCPtr, this, index, value);
  }

  public void SetBackwardSequence(long index, int[] value) {
    operations_research_constraint_solverJNI.SequenceVarLocalSearchOperator_SetBackwardSequence(swigCPtr, this, index, value);
  }

}
