/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class SymmetryBreaker extends DecisionVisitor {
  private transient long swigCPtr;

  protected SymmetryBreaker(long cPtr, boolean cMemoryOwn) {
    super(operations_research_constraint_solverJNI.SymmetryBreaker_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SymmetryBreaker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_SymmetryBreaker(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.SymmetryBreaker_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.SymmetryBreaker_change_ownership(this, swigCPtr, true);
  }

  public SymmetryBreaker() {
    this(operations_research_constraint_solverJNI.new_SymmetryBreaker(), true);
    operations_research_constraint_solverJNI.SymmetryBreaker_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void AddIntegerVariableEqualValueClause(IntVar var, long value) {
    operations_research_constraint_solverJNI.SymmetryBreaker_AddIntegerVariableEqualValueClause(swigCPtr, this, IntVar.getCPtr(var), var, value);
  }

  public void AddIntegerVariableGreaterOrEqualValueClause(IntVar var, long value) {
    operations_research_constraint_solverJNI.SymmetryBreaker_AddIntegerVariableGreaterOrEqualValueClause(swigCPtr, this, IntVar.getCPtr(var), var, value);
  }

  public void AddIntegerVariableLessOrEqualValueClause(IntVar var, long value) {
    operations_research_constraint_solverJNI.SymmetryBreaker_AddIntegerVariableLessOrEqualValueClause(swigCPtr, this, IntVar.getCPtr(var), var, value);
  }

}
