/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class UnsortedNullableRevBitset {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnsortedNullableRevBitset(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsortedNullableRevBitset obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_UnsortedNullableRevBitset(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsortedNullableRevBitset(int bit_size) {
    this(operations_research_constraint_solverJNI.new_UnsortedNullableRevBitset(bit_size), true);
  }

  public void Init(Solver solver, SWIGTYPE_p_std__vectorT_unsigned_long_long_t mask) {
    operations_research_constraint_solverJNI.UnsortedNullableRevBitset_Init(swigCPtr, this, Solver.getCPtr(solver), solver, SWIGTYPE_p_std__vectorT_unsigned_long_long_t.getCPtr(mask));
  }

  public boolean RevSubtract(Solver solver, SWIGTYPE_p_std__vectorT_unsigned_long_long_t mask) {
    return operations_research_constraint_solverJNI.UnsortedNullableRevBitset_RevSubtract(swigCPtr, this, Solver.getCPtr(solver), solver, SWIGTYPE_p_std__vectorT_unsigned_long_long_t.getCPtr(mask));
  }

  public boolean RevAnd(Solver solver, SWIGTYPE_p_std__vectorT_unsigned_long_long_t mask) {
    return operations_research_constraint_solverJNI.UnsortedNullableRevBitset_RevAnd(swigCPtr, this, Solver.getCPtr(solver), solver, SWIGTYPE_p_std__vectorT_unsigned_long_long_t.getCPtr(mask));
  }

  public int ActiveWordSize() {
    return operations_research_constraint_solverJNI.UnsortedNullableRevBitset_ActiveWordSize(swigCPtr, this);
  }

  public boolean Empty() {
    return operations_research_constraint_solverJNI.UnsortedNullableRevBitset_Empty(swigCPtr, this);
  }

  public boolean Intersects(SWIGTYPE_p_std__vectorT_unsigned_long_long_t mask, SWIGTYPE_p_int support_index) {
    return operations_research_constraint_solverJNI.UnsortedNullableRevBitset_Intersects(swigCPtr, this, SWIGTYPE_p_std__vectorT_unsigned_long_long_t.getCPtr(mask), SWIGTYPE_p_int.getCPtr(support_index));
  }

  public long bit_size() {
    return operations_research_constraint_solverJNI.UnsortedNullableRevBitset_bit_size(swigCPtr, this);
  }

  public long word_size() {
    return operations_research_constraint_solverJNI.UnsortedNullableRevBitset_word_size(swigCPtr, this);
  }

  public SWIGTYPE_p_operations_research__RevIntSetT_int_t active_words() {
    return new SWIGTYPE_p_operations_research__RevIntSetT_int_t(operations_research_constraint_solverJNI.UnsortedNullableRevBitset_active_words(swigCPtr, this), false);
  }

}
