/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class VoidToString {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VoidToString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VoidToString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        operations_research_constraint_solverJNI.delete_VoidToString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    operations_research_constraint_solverJNI.VoidToString_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    operations_research_constraint_solverJNI.VoidToString_change_ownership(this, swigCPtr, true);
  }

  public String run() {
    return operations_research_constraint_solverJNI.VoidToString_run(swigCPtr, this);
  }

  public VoidToString() {
    this(operations_research_constraint_solverJNI.new_VoidToString(), true);
    operations_research_constraint_solverJNI.VoidToString_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
